// import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
// import { ReactNode, useEffect } from 'react';
"use client"
import { CopilotKit } from '@copilotkit/react-core';
import "./globals.css";
import AOS from 'aos';
import 'aos/dist/aos.css'; // Import AOS styles
import { useEffect } from 'react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration
      easing: 'ease-in-out', // Animation easing
    });
  }, []);

  return (
    <html lang="en">
      <body>
        <CopilotKit
          runtimeUrl='https://api.copilotkit.com/v1/runtime'
          publicApiKey='ck_pub_49341add514bd1f5e1b263594cc27490'
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
